### ISSUE TITLE
Cannot build with node 0.11.14

### ISSUE THREAD

**Issue by idy** [Voxer/sse4_crc32#15]
```shell

> sse4_crc32@2.1.0 install /home/fir/fir-sync/node_modules/sse4_crc32
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/fir/fir-sync/node_modules/sse4_crc32/build'
  CXX(target) Release/obj.target/sse4_crc32/src/sse4_crc32.o
In file included from ../src/sse4_crc32.cpp:11:
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanError(const char*)’:
../node_modules/nan/nan.h:318: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In function ‘void NanThrowError(const char*)’:
../node_modules/nan/nan.h:322: error: ‘ThrowException’ is not a member of ‘v8’
../node_modules/nan/nan.h:322: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In function ‘void NanThrowError(v8::Handle<v8::Value>)’:
../node_modules/nan/nan.h:327: error: ‘ThrowException’ is not a member of ‘v8’
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanError(const char*, int)’:
../node_modules/nan/nan.h:334: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h:336: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h:336: error: no matching function for call to ‘v8::Integer::New(const int&)’
/home/fir/.node-gyp/0.11.14/deps/v8/include/v8.h:1989: note: candidates are: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanTypeError(const char*)’:
../node_modules/nan/nan.h:348: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In function ‘void NanThrowTypeError(const char*)’:
../node_modules/nan/nan.h:352: error: ‘ThrowException’ is not a member of ‘v8’
../node_modules/nan/nan.h:352: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In function ‘v8::Handle<v8::Value> NanRangeError(const char*)’:
../node_modules/nan/nan.h:356: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In function ‘void NanThrowRangeError(const char*)’:
../node_modules/nan/nan.h:360: error: ‘ThrowException’ is not a member of ‘v8’
../node_modules/nan/nan.h:360: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In constructor ‘NanCallback::NanCallback(const v8::Local<v8::Function>&)’:
../node_modules/nan/nan.h:668: error: no matching function for call to ‘v8::Object::New()’
/home/fir/.node-gyp/0.11.14/deps/v8/include/v8.h:2372: note: candidates are: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
../node_modules/nan/nan.h:669: error: ‘NewSymbol’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In destructor ‘NanCallback::~NanCallback()’:
../node_modules/nan/nan.h:675: error: ‘class v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >’ has no member named ‘Dispose’
../node_modules/nan/nan.h:676: error: ‘class v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >’ has no member named ‘Clear’
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Function> NanCallback::GetFunction()’:
../node_modules/nan/nan.h:680: error: ‘NewSymbol’ is not a member of ‘v8::String’
../node_modules/nan/nan.h:681: error: expected primary-expression before ‘>’ token
../node_modules/nan/nan.h:681: error: expected primary-expression before ‘)’ token
../node_modules/nan/nan.h: In member function ‘void NanCallback::Call(int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:693: error: ‘NewSymbol’ is not a member of ‘v8::String’
../node_modules/nan/nan.h:693: error: expected primary-expression before ‘>’ token
../node_modules/nan/nan.h:693: error: expected primary-expression before ‘)’ token
../node_modules/nan/nan.h:695: error: ‘GetCurrent’ is not a member of ‘v8::Context’
../node_modules/nan/nan.h: In member function ‘void NanAsyncWorker::SavePersistent(const char*, v8::Local<v8::Object>&)’:
../node_modules/nan/nan.h:739: error: ‘NewSymbol’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Object> NanAsyncWorker::GetFromPersistent(const char*)’:
../node_modules/nan/nan.h:746: error: ‘NewSymbol’ is not a member of ‘v8::String’
../node_modules/nan/nan.h:746: error: expected primary-expression before ‘>’ token
../node_modules/nan/nan.h:746: error: expected primary-expression before ‘)’ token
../node_modules/nan/nan.h: In member function ‘virtual void NanAsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:768: error: ‘New’ is not a member of ‘v8::String’
../node_modules/nan/nan.h: In function ‘char* NanFromV8String(v8::Handle<v8::Value>, Nan::Encoding, size_t*, char*, size_t, int)’:
../node_modules/nan/nan.h:987: error: ‘AsciiValue’ is not a member of ‘v8::String’
../node_modules/nan/nan.h:987: error: expected ‘;’ before ‘value’
../node_modules/nan/nan.h:1050: error: ‘value’ was not declared in this scope
../src/sse4_crc32.cpp: In function ‘void calculate(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/sse4_crc32.cpp:33: error: no matching function for call to ‘v8::Integer::New(int)’
/home/fir/.node-gyp/0.11.14/deps/v8/include/v8.h:1989: note: candidates are: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
../src/sse4_crc32.cpp:33: error: return-statement with a value, in function returning 'void'
../src/sse4_crc32.cpp:64: error: no matching function for call to ‘v8::Integer::NewFromUnsigned(uint32_t&)’
/home/fir/.node-gyp/0.11.14/deps/v8/include/v8.h:1990: note: candidates are: static v8::Local<v8::Integer> v8::Integer::NewFromUnsigned(v8::Isolate*, uint32_t)
../src/sse4_crc32.cpp:64: error: return-statement with a value, in function returning 'void'
../src/sse4_crc32.cpp: In function ‘void init(v8::Handle<v8::Object>)’:
../src/sse4_crc32.cpp:72: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/sse4_crc32.cpp:72: error: no matching function for call to ‘v8::FunctionTemplate::New(void (&)(const v8::FunctionCallbackInfo<v8::Value>&))’
/home/fir/.node-gyp/0.11.14/deps/v8/include/v8.h:3434: note: candidates are: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, void (*)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
In file included from ../src/sse4_crc32.cpp:11:
../node_modules/nan/nan.h: In function ‘void NanDispose(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&) [with T = v8::Object]’:
../node_modules/nan/nan.h:717:   instantiated from here
../node_modules/nan/nan.h:373: error: ‘class v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >’ has no member named ‘Clear’
make: *** [Release/obj.target/sse4_crc32/src/sse4_crc32.o] Error 1
make: Leaving directory `/home/fir/fir-sync/node_modules/sse4_crc32/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
     at ChildProcess.onExit (/home/fir/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 2.6.32-431.3.1.el6.x86_64
gyp ERR! command "node" "/home/fir/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fir/fir-sync/node_modules/sse4_crc32
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by pierreinglebert** [comment]
it's fixed in https://github.com/Voxer/sse4_crc32/pull/14

**Comment by anandsuresh** [comment]
Just released v2.1.1 with #14 merged. Please update your dependencies.
